---
- name: Install apache
#  become: yes
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - httpd

#- name: Enable package
#  service:
#    name: "{{ item }}"
#    state: started
#    with_items:
#        - "smb"
#        - "nmb"
