---
- name: Install bind
  become: yes
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - bind

- name: Enable package
  service:
    name: "{{ item }}"
    state: started
  with_items:
        - named

- name: copy template over
  template:
    src: templates/named.config.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0644

- name: copy named config additions file
  copy:
    src: "files/{{ item.name }}"
    dest: "{{ item.path }}/{{ item.name }}"
    owner: root
    group: named
    mode: 0644
  with_items:
    - { name: named.chicken.zone, path: /etc/ }
    - { name: magicalchicken.zone, path: /var/named/ }

