---
- name: Install Packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
  - bind-utils      
  - epel-release
  - mailx
  - wget
  - rsync

- include: vmware.yml
- include: selinux.yml
- include: yum_client.yml
